### ISSUE TITLE
Decode font materialize

### ISSUE THREAD

**Issue by silviomm** [silviomm/openblog#1]
Failed to decode downloaded font: http://localhost:3000/font/roboto/Roboto-Regular.woff2

**Comment by silviomm** [comment]
now its on public/font

**Comment by minooo** [comment]
@silviomm hello，I have the same problem, I don not know how to do with it;
[this is my problem](https://github.com/minooo/CSS-Modules-----React)
when you run `npm install` and `npm start`,open `localhost:5000`
you can see the problem like this 
![image](https://cloud.githubusercontent.com/assets/9410091/14010823/a260517c-f1d3-11e5-8bb3-6924ff9fd30a.png)
Any ideas? Thanks so much!

**Comment by silviomm** [comment]
hello,

Well, I'm using Meteor, and althought Meteor is build on top of nodejs, I
dont know the file structure. But I fixed by putting my fonts into
public/font. In your case, I guess it would be src/public/font. Sorry that
I cant help with more info.

**Comment by minooo** [comment]
Thank you all the same!

**Comment by silviomm** [comment]
Have you tried a public folder outside /src? Same level as server.js

**Comment by minooo** [comment]
@silviomm yeah, I have tried. just the same result.
![image](https://cloud.githubusercontent.com/assets/9410091/14036430/c22f2564-f273-11e5-9f1a-f1e039f6cfc3.png)
Although the web works well, but the console makes me feel uneasy :(
